services:
  mysql:
    image: mysql:lts
    container_name: tv-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d/

  flask:
    build: ./flask
    container_name: flask-web
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  tv_startup:
    build: ./tv_startup
    container_name: tv-startup
    restart: unless-stopped
    depends_on:
      - mysql

volumes:
  mysql_data:
